Repository adit2005/Hacktoberfest_23_ML_models, pull requests merged in 2023-10, with the labels that each got.

#2 added model for Parkinson Detection
  models/parkinsons.ipynb
Labels: hacktoberfest accepted, hacktoberfest, Hacktoberfest-approved, Hacktoberfest2023

#7 Added a Model to detect Parkinson
  models/parkinsons.ipynb
Labels: open source, hacktoberfest accepted, Hacktoberfest2023, Hacktoberfest-approved, good first issue

#8 Lung Cancer Analysis
  models/Lung Cancer Analysis.ipynb
Labels: open source, hacktoberfest accepted, Hacktoberfest2023, Hacktoberfest-approved, good first issue

#10 Added Alzheimer's Prediction Model
  models/AlzheimerPrediction.ipynb
Labels: open source, Hacktoberfest2023, Hacktoberfest-approved, good first issue, hacktoberfest-accepted
